[package]
name = "dump1090_rs"
version = "0.5.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "3.0.0", features = ["color", "derive", "wrap_help"]}
num-complex = "0.4"
soapysdr = "0.3"
libdump1090_rs = { path = "../", version = "0.5" }
hex = "0.4"
toml = "0.5.8"
serde = { version = "1.0", features = ["derive"] }
